---
name: lvm-pixelflat
short: configuration file for master pixelflat creation
description: |
  defines the reduction steps to create a master pixelflat.
location: "[CALIB_PATH]/[DRPVER]/"
naming_convention: lvm-pixelflat-[CAMERA]-[EXPTIME]-config.yaml
target_frame: lvm-pixelflat
calibration_frames:
  bias: lvm-mbias
  dark: lvm-mdark
reduction_steps:
  imageMethod.basicCalibration:
    in_image: lvm-pixelflat
    out_image: lvm-pixelflat
    in_bias: lvm-mbias
    in_dark: lvm-mdark
  imageMethod.createMasterFrame:
    in_images: lvm-pixelflat
    out_image: lvm-mpixelflat
    reject_cr: true
...