---
name: lvm-mdark
short: configuration file for master dark creation
description: |
  defines the reduction steps to create a master dark.
location: "[CALIB_PATH]/[DRPVER]/"
naming_convention: lvm-mdark-[CAMERA]-[EXPTIME]-config.yaml
target_frame: lvm-dark
calibration_frames:
  bias: lvm-mbias
reduction_steps:
  imageMethod.basicCalibration:
    in_image: lvm-dark
    out_image: lvm-dark
    in_bias: lvm-mbias
  imageMethod.createMasterFrame:
    in_images: lvm-dark
    out_image: lvm-mdark
    reject_cr: true
...