---
name: lvm-mbias
short: configuration file for master bias creation
description: |
  defines the reduction steps to create a master bias.
location: "[CALIB_PATH]/[DRPVER]/"
naming_convention: lvm-mbias-[CAMERA]-config.yaml
target_frame: lvm-bias
calibration_frames:
reduction_steps:
  imageMethod.createMasterFrame:
    in_images: lvm-bias
    out_image: lvm-mbias
    reject_cr: false
...