---
name: lvm-bias
short: configuration file for bias calibration
description: |
  defines the reduction steps to create a calibrated bias.
location: "[CALIB_PATH]/[DRPVER]/"
naming_convention: lvm-bias-[CAMERA]-[EXPNUM]-config.yaml
target_frame: lvmSdr
calibration_frames: null
reduction_steps:
  imageMethod.preprocRawFrame:
    in_image: lvmSdr
    out_image: lvm-pframe
    unit: ADU
    compute_error: false
...