name: lvm-preproc
short: preprocessing for calibration frames (bias, dark, pixelflat)
description: |
  defines the preprocessing step for calibration frames, which does not require Poisson error calculation and
  data units are set to ADU.
location: "[CALIB_PATH]/[DRPVER]/"
naming_convention: lvm-preproc-[IMAGETYP]-[HEMI]-[CAMERA]-[EXPNUM]-config.yaml
target_frame: lvmSdr
calibration_frames:
reduction_steps:
  imageMethod.preprocRawFrame:
    in_image: lvmSdr
    out_image: lvm-[IMAGETYP]
    unit: ADU
    compute_error: false