---
short: "quick LVM Data Reduction Pipeline (DRP) configuration file"
description: |
  "defines the target frame, calibration frames and DRP steps to perform the quick DRP for frame validation"
location: null
naming_convention: null
metadata:
  drp_ver: 0.1.0
target_frame: lvmSdr
calibration_frames:
  bias: lvmMBias
  dark: lvmMDark
  pixelflat: lvmMPix
  fiberflat: lvmMFlat
  arc: lvmMArc
reduction_steps:
  imageMethod.preprocRawFrame:
    in_image: lvmSdr
    out_image: lvmPre
    compute_error: true
    unit: "e-"
  imageMethod.basicCalibration:
    in_image: lvmPre
    out_image: lvmCal
    in_bias: lvmMBias
    in_dark: lvmMDark
    in_pixelflat: lvmMPix
  imageMethod.extractSpec:
    in_image: lvmCal
    out_rss: lvmFrame
    in_fiberflat: lvmMFlat
    method: "aperture"
    aperture: 7 #median of the distance between peaks (from the mid region trace)
  rssMethod.createPixTable:
    rss_in: lvmFrame
    rss_out: lvmWFrame
    in_arc: lvmMArc
  rssMethod.joinChannels:
  rssMethod.quickQuality:
    # SN in several bands (FWHM=100AA)
    # locate sky lines (match against a known list)
    # measure sky lines width
    # sky lines equivalent width
  # for quick flux calibration:
  # * get solar spectrum
  # * normalize solar spectrum by fiberflat
  # apply fiber flat
  # perform basic flux calibration (theoric response function)
...