rm -rf desici/
rm -rf desicmx/
rm -rf desietc/
rm -rf desihub.github.io/
rm -rf desimodel/
rm -rf desimodelDATA/
rm -rf desimodules/
rm -rf desisim-testdata/
rm -rf desisim/
rm -rf desispec/
rm -rf desisurvey/
rm -rf desitarget/
rm -rf desitemplate/
rm -rf desitest/
rm -rf desiutil/
rm -rf fiberassign/
rm -rf lvm-notebooks/
rm -rf nightwatch/
rm -rf prospect/
rm -rf redrock-templates/
rm -rf redrock/
rm -rf simqso/
rm -rf specex/
rm -rf specsim/
rm -rf specter/
rm -rf src/
rm -rf surveysim/
rm -rf teststand/
rm -rf tilepicker/
rm -rf tutorials/

git clone https://github.com/desihub/desici&
git clone https://github.com/desihub/desicmx&
git clone https://github.com/desihub/desietc&
git clone https://github.com/desihub/desihub.github.io&
git clone https://github.com/desihub/desimodel&
git clone https://github.com/desihub/desidatamodel&
git clone https://github.com/desihub/desimodules&
git clone https://github.com/desihub/desisim-testdata&
git clone https://github.com/desihub/desisim&
git clone https://github.com/desihub/desispec&
git clone https://github.com/desihub/desisurvey&
git clone https://github.com/desihub/desitarget&
git clone https://github.com/desihub/desitemplate&
git clone https://github.com/desihub/desitest&
git clone https://github.com/desihub/desiutil&
git clone https://github.com/desihub/fiberassign&
git clone https://github.com/desihub/lvm-notebooks&
git clone https://github.com/desihub/nightwatch&
git clone https://github.com/desihub/prospect&
git clone https://github.com/desihub/redrock-templates&
git clone https://github.com/desihub/redrock&
git clone https://github.com/desihub/simqso&
git clone https://github.com/desihub/specex&
git clone https://github.com/desihub/specsim&
git clone https://github.com/desihub/specter&
git clone https://github.com/desihub/src&
git clone https://github.com/desihub/surveysim&
git clone https://github.com/desihub/teststand&
git clone https://github.com/desihub/tilepicker&
git clone https://github.com/desihub/tutorials&
